# version: '3.8' # Puedes borrar esta línea

services:
  # --- Servicio Nginx ---
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - /c/laragon/www/cgs-ptolemaic:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-net
    depends_on:
      - php

  # --- Servicio PHP-FPM ---
  php:
    container_name: laravel_php84_fpm
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - /c/laragon/www/cgs-ptolemaic:/var/www/html
    networks:
      - laravel-net

  # --- Servicio PostgreSQL --- 🐘
  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    restart: unless-stopped
    environment:
      POSTGRES_DB: ptolemaic
      POSTGRES_USER: ptolomeo
      POSTGRES_PASSWORD: 52393811
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel-net

# --- Definición de la Red --- (Solo UNA vez)
networks:
  laravel-net:
    driver: bridge